### ISSUE TITLE
package name instead of source name is written to failed_sources.csv

### ISSUE THREAD

**Issue by ndkv** [openstate/CKAN-Link-Checker#5]
Lines 187, 205 and 227 of [check_ckan_links.py](https://github.com/openstate/CKAN-Link-Checker/blob/master/check_ckan_links.py) should read 

``` python
resource['name']
```

instead of 

``` python
package['name']
```

**Comment by siccovansas** [comment]
I choose to list the package name because the resource name does not consistently give a useful name. E.g., there are resource names like ["29"](https://data.overheid.nl/data/api/3/action/package_show?id=belaste-woningen-geur-industriele-bedrijven), ["1"](https://data.overheid.nl/data/api/3/action/package_show?id=provinciaal-arbeidsplaatsen-register-par) or even [nothing](https://data.overheid.nl/data/api/3/action/package_show?id=01-bve-adressen-instellingen--ministerie-van-ocw). So the package name simply gives some extra context on top of the specific URL of the failed resource.
